### ISSUE TITLE
`insert into A select * from A`?

### ISSUE THREAD

**Issue by rliang** [koskimas/kysely#36] opened 2021-12-13 11:57 UTC
It doesn't seem possible to chain `db.insertInto("A").selectFrom("A").selectAll()`.

It that possible in some other way? A workaround is to first fetch the rows from A and then insert them, however that incurs an extra roundtrip to the database.

**Comment by koskimas** [comment] 2021-12-13 12:09
Yep, that's not supported at the moment and this is a tricky one.

Kysely only has one query builder and not separate ones for different queries like `SelectQueryBuilder`, `InsertQueryBuilder` etc.. There's a good reason for that, but I won't get into details here. Since we only have a single query builder lass, adding a `selectFrom` method to the query builder would be confusing. For example, people would be able do both of these:

```ts
db.selectFrom('person').selectFrom('pet').select(['pet.name', 'person.first_name'])
db.insertInto('person').selectFrom('pet').select(['pet.name', 'person.first_name'])
```

You can probably spot the problem here. The first one is ok, but the second one should produce an error because you can't insert rows `("name", "first_name")` into `person`. So we would need to have different types for those methods based on the query type. With one single `QueryBuilder` class, that's difficult. It's possible, but would make the types super ugly and hard to maintain.

Another option would be to allow a subquery in `values`:

```ts
db.insertInto('A').values((eb) => eb.selectFrom('B').selectAll())
```

but the problem here is that people would expect `values` to produce a `values` statement and nothing else.

Do you have any ideas for the API?

**Comment by rliang** [comment] 2021-12-13 12:21
I don't know about the details that you mentioned, and I'm sure it would be a lot of work, but I think having multiple query builders would be the most correct option.

Even more so considering that you can currently write
```ts
db.selectFrom(...).values(...).set(...)
```
This obviously results in invalid SQL, but Typescript cannot detect that at compile-time, which weakens the library's purpose.

Nevertheless, thank you again for the quick reply!

**Comment by koskimas** [comment] 2021-12-13 12:50
It's not that it's a lot of work, but it would make the code far less maintainable due to copy-pasting or optionally insane unreadable generic types. It's a tradeoff between maintainability and usability.

**Comment by koskimas** [comment] 2021-12-13 15:26
> which weakens the library's purpose

Really? Feel free to use knex.

**Comment by koskimas** [comment] 2021-12-14 21:46
I think you are right. Separate query builders is the way to go after all. I'll go with the copy-paste option and not the insane types option.

After we have a separate InsertQueryBuilder, the query in this issue can be cleanly implemented.

**Comment by koskimas** [comment] 2021-12-15 10:07
About the original issue. The most natural API for it would clearly be

```ts
db.insertInto('person').selectFrom('something').select(...)
```

but that would creating a duplicate of the `SelectQueryBuilder`. I mean completely copy-pasting the `SelectQueryBuilder` which is over thousand lines of code. For the reasons explained in the comment above, it's impossible to inherit `SelectQueryBuilder`. We also can't just return a `SelectQueryBuilder` from `selectFrom` of the `InsertQueryBuilder` because then `execute` would execute the select query.

I propose this API:

```ts
db.insertInto('person').expression((eb) => eb.selectFrom('somethibg').select(...))
```

That way we can use `SelectQueryBuilder` inside the callback to create the select query. You can also call `eb.raw` to create a completely raw insert.

**Comment by koskimas** [comment] 2021-12-15 12:57
This would also work

```t
db.insertInto('person').expression(db.selectFrom('something').select(...))
```

**Comment by koskimas** [comment] 2021-12-15 13:03
This is now implemented and will be released with the next version.

**Closed** 2021-12-15 13:02 UTC
