### ISSUE TITLE
Dynamic import failures when used with bundlers like esbuild

### ISSUE THREAD

**Issue by samsouder** [koskimas/kysely#54] opened 2022-01-10 16:16 UTC
Hi again @koskimas! I am back with another issue that has come up while trying to deploy an app with Kysely when using the recommended AWS Lambda deployment strategy of using esbuild.

Now that the Lambda is running we can't actually get Kysely to load due to dynamic imports of the database pool creation function (https://github.com/koskimas/kysely/blob/17e190b4b46af8b7363cba16e57be05d597e34a8/src/dialect/mysql/mysql-driver.ts#L122). Since esbuild is essentially throwing all referenced code into one giant JS file there is no ability to import dynamically that I know of (without of course moving to a manual bundling which we are trying hard not to do if possible).

I was able to manually modify the locally installed and bundled Kysely package to directly use the mysql2 `createPool` function to ensure that everything does indeed load up if it were able to be bundled directly.

I realize this isn't your problem, per se, but I was hoping you might have some thoughts and advice for folks in our scenario.

**Comment by koskimas** [comment] 2022-01-10 16:29
So you are using the mysql dialect directly and not something like [this](https://github.com/serverless-stack/kysely-data-api)

We can't remove the dynamic imports. If we do, all users need to install all dialect's drivers even if they only use one.

I don't understand why esbuild doesn't know how to do dynamic imports? Even though it generates one blob, surely all imports are mapped to some data structure? Why can't that same data structure be used to figure out dynamic imports? Isn't that how webpack works?

**Comment by koskimas** [comment] 2022-01-10 16:35
Ok, so I did a bit of googling and it seems that esbuild would support string literal imports like:

```ts
cosnt dep = await import('dep')
```

but the problem is expression imports like


```ts
const s = 'dep'
cosnt dep = await import(s)
```

**Comment by samsouder** [comment] 2022-01-10 16:59
Correct, If I manually change your library to use the following code the bundler sees the import and replaces it with a function that returns the expected object instead of trying to let `node` load it from the filesystem.

```
async function importMysqlPoolFactory() {
    try {
        // return await importNamedFunction('mysql2', 'createPool');
        return (await import ('mysql2')).createPool;
    }
    catch (error) {
        throw new Error('MySQL client not installed. Please run `npm install mysql2`');
    }
}
```

**Comment by koskimas** [comment] 2022-01-10 17:02
Ok. I'll get rid of the helper then. It's not as simple as that though. Many packages produce different results when ESM is enabled for the project and when using commonjs for some reason.

The next version will be released in couple of minutes.

**Closed** 2022-01-10 17:06 UTC

**Comment by koskimas** [comment] 2022-01-10 17:28
0.16.4 fixes this.
